[phases.build]
  cmds = ["...", "java -Djarmode=layertools -jar target/*-exec.jar extract"]
[start]
  runImage = "eclipse-temurin:17-jdk-alpine"
  onlyIncludeFiles = [
    { from = './dependencies/', to = './' },
    { from = './snapshot-dependencies/', to = './' },
    { from = './spring-boot-loader/', to = './' },
    { from = './application/', to = './' }
  ]
  cmd = "$JAVA_HOME/bin/java -Dserver.port=$PORT $JAVA_OPTS org.springframework.boot.loader.JarLauncher"
